### ISSUE TITLE
implement RxJS-like BehaviorSubject

### ISSUE THREAD

**Issue by TylorS** [TylorS/most-subject#3]
# Overview

Create a subject which behaves similarly to RxJS' [BehaviorSubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md)

# Motivation 

Easier transitioning from RxJS to *Most*

**Comment by TylorS** [comment]
@briancavalier @Frikki

Any suggestions on better naming?

**Comment by axefrog** [comment]
If I were naming this I'd first try to describe its behaviour.

- It always retains the latest value
- It has an initial value to be used before anything has been emitted
- It emits (replays?) the currently-retained value to new subscribers

How to say this in a class name? Ideas:

- **RetainedValue**Subject
- **Retention**Subject
- **ValueRetention**Subject
- **LatestValue**Subject
- **RecentValue**Subject
- **ValueCapture**Subject
- **SingleCapture**Subject
- **CaptureLatest**Subject
- **ReplayOnce**Subject
- **SingularReplay**Subject

**Comment by TylorS** [comment]
I'm actually beginning to wonder if it would be a better to simply provide a single function with options instead. No real reason to continue to emulate RxJS.
e.g.
```js
const {sink, stream} = subject() // regular subject 
const {sink, stream} = subject({replay: true}) // replaySubject
const {sink, stream} = subject({replay: true, initialValue: 1}) // behaviorSubject
```

**Comment by wishfoundry** [comment]
I would vote for something like 
```javascript
 const {sink, stream}  cacheLatest(size: number)
sink.add(initial)
```

supporting an initial value in the constructor seems superfluous at best, especially for buffers > 1.

**Comment by TylorS** [comment]
I actually went ahead with a similar API to the above. If you check the README now, it has the API I decided upon. It *does* include the initial values.
