### ISSUE TITLE
window.most-subject would be useful

### ISSUE THREAD

**Issue by dschalk** [TylorS/most-subject#9]
I have the Bower most.js file referenced in index.html script tags. The file supports my monad.js file, which is referenced in script tags below it. This setup facilitates experimentation in the browser console. I import the npm  most package, along with the motorcycle package, in my main application file.

Now I want to define some things in monad.js that depend on most-subject. I need to put something in script tags under most.js and above monad.js. Any suggestions? Any chance something along the lines of the most.js file will become available on Bower?

**Comment by dschalk** [comment]
UPDATE: I added "window.subject = subject;" and "window.create = create" to my main.js file, which imports `most-subject` from `node_modules`. I added the most-subject README 1, 2, 3 demo to monad.js in a setTimeout so main.js would have time to make `subject` and `create` window methods. I loaded my app in Chrome, and after a delay, "1, 2, 3" appeared in the console.

I guess I will be able to put everything that relies on most-subject in the setTimeout function and accomplish my goal. I still suggest, if it wouldn't be too much trouble, that you consider making a script file available in your repo, the NPM library, or Bower.

**Comment by TylorS** [comment]
I definitely agree, I will add this to my list of todos :+1:

**Comment by TylorS** [comment]
PR is welcome if you feel inclined. I'll probably do it with browserify + babelify + browserify-shim

**Comment by dschalk** [comment]
I'm glad to hear that. The idea in my update turned out to be a fiasco. I am defining everything that needs most-subject in my main.js function for the time being.

**Comment by dschalk** [comment]
`most-subject` works like a charm. http://schalk.net:3077

**Comment by TylorS** [comment]
There is now a dist/ build from #12
